---
- name: SolarWinds Papertrail Network 
  hosts: all

  tasks: 
    - name: Solarwinds Papertrail Network Device Config
      register: "papertrail_script"
      ansible.builtin.shell: |
        econfigure terminal
        logging host logsN.papertrailapp.com transport udp port XXXXX
        logging facility syslog
        logging trap debugging
        exit
