---
- name: SolarWinds Papertrail
  hosts: localhost

  tasks: 
    - name: Solarwinds Papertrail
      register: "papertrail_script"
      ansible.builtin.shell: |
         wget -qO - --header=X-Papertrail-Token\:\ N54KLbED0gZgQXIfAem https://papertrailapp.com/destinations/28641001/setup.sh 

