---
- name: SolarWinds Papertrail
  hosts: all

  tasks:
    - name: Run a command to reg device with papertrail.
      raw: wget -qO - --header="X-Papertrail-Token':' N54KLbED0gZgQXIfAem" \https://papertrailapp.com/destinations/28641001/setup.sh 
      args:
        executable: sudo /bin/bash